# Generated by Django 3.0.5 on 2020-04-20 00:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process_or_Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Process_or_function_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fmea_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 20, 0, 16, 12, 174805, tzinfo=utc))),
                ('Potential_Failure_Mode', models.CharField(max_length=256)),
                ('Potential_Effects_of_Failure', models.CharField(max_length=256)),
                ('Sev', models.IntegerField()),
                ('Class', models.CharField(blank=True, max_length=10, null=True)),
                ('Potential_causes_or_Mechanisms_of_Failure', models.CharField(max_length=256)),
                ('Occ', models.IntegerField()),
                ('Current_Process_Control_Prevention', models.CharField(max_length=256)),
                ('Current_Process_Control_Detection', models.CharField(max_length=256)),
                ('Det', models.IntegerField()),
                ('RPN', models.IntegerField()),
                ('Recommended_Actions', models.CharField(blank=True, max_length=256, null=True)),
                ('Resp_Target_Date', models.CharField(blank=True, max_length=256, null=True)),
                ('Actions_Taken', models.CharField(blank=True, max_length=256, null=True)),
                ('Sev_Rev', models.IntegerField(blank=True, null=True)),
                ('Occ_Rev', models.IntegerField(blank=True, null=True)),
                ('Det_Rev', models.IntegerField(blank=True, null=True)),
                ('RPN_Rev', models.IntegerField(blank=True, null=True)),
                ('Rev_No', models.IntegerField(blank=True, null=True)),
                ('Rev_Date', models.DateField(blank=True, null=True)),
                ('Rev_History', models.CharField(blank=True, max_length=256, null=True)),
                ('Part_Name', models.ManyToManyField(blank=True, null=True, to='fmea_app.Part_name')),
                ('Process_OR_Function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmea_app.Process_or_Function')),
            ],
        ),
    ]
