# Generated by Django 3.0.5 on 2020-04-20 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0002_auto_20200420_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmea_record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 20, 13, 44, 53, 606671, tzinfo=utc)),
        ),
    ]
